{
 "title": "Demo Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "service", "query": { "query": "latency_bucket" } }
  ]
 },
 "panels": [
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Recommendation Service (CPU%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(runtime_cpython_cpu_time_seconds_total{type=~\"system\"}[$__interval])*100",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(runtime_cpython_cpu_time_seconds_total{type=~\"user\"}[$__interval])*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Recommendation Service (Memory)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "rate(runtime_cpython_memory_bytes_total{type=~\"rss|vms\"}[$__interval])/1024/1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Recommendations Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(app_recommendations_counter_total{recommendation_type=\"catalog\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "rate(calls_total{status_code=\"STATUS_CODE_ERROR\"}[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}